-- =====================================================================
-- Proyecto Integrador 2026-2 - Avance 1: Núcleo transaccional
-- Empresa : Cine Aurora (grupo Cinemas 8) - Bogotá D.C., Colombia
-- Script  : 01_creacion_tablas.sql
-- Motor   : PostgreSQL
-- Modelo  : 11 tablas
--           - 8 entidades requeridas: actores_directores, contratos,
--             salas, funciones, tipos_boleta, ventas, espectadores, staff
--           - 1 entidad de apoyo: peliculas
--           - 2 entidades asociativas: detalle_ventas, funcion_staff
-- =====================================================================

-- Permite volver a ejecutar el script desde cero
DROP TABLE IF EXISTS funcion_staff       CASCADE;
DROP TABLE IF EXISTS detalle_ventas      CASCADE;
DROP TABLE IF EXISTS ventas              CASCADE;
DROP TABLE IF EXISTS funciones           CASCADE;
DROP TABLE IF EXISTS contratos           CASCADE;
DROP TABLE IF EXISTS espectadores        CASCADE;
DROP TABLE IF EXISTS tipos_boleta        CASCADE;
DROP TABLE IF EXISTS staff               CASCADE;
DROP TABLE IF EXISTS salas               CASCADE;
DROP TABLE IF EXISTS peliculas           CASCADE;
DROP TABLE IF EXISTS actores_directores  CASCADE;

-- 1. ACTORES_DIRECTORES
CREATE TABLE actores_directores (
    id_actor_director  INTEGER GENERATED BY DEFAULT AS IDENTITY,
    nombre_artistico   VARCHAR(100) NOT NULL,
    nombre_completo    VARCHAR(150) NOT NULL,
    rol                VARCHAR(10)  NOT NULL,
    nacionalidad       VARCHAR(60),
    fecha_nacimiento   DATE,
    email_contacto     VARCHAR(120),
    CONSTRAINT pk_actores_directores PRIMARY KEY (id_actor_director),
    CONSTRAINT ck_ad_rol    CHECK (rol IN ('Actor', 'Director', 'Ambos')),
    CONSTRAINT ck_ad_nombre CHECK (btrim(nombre_artistico) <> '' AND btrim(nombre_completo) <> ''),
    CONSTRAINT ck_ad_nacim  CHECK (fecha_nacimiento IS NULL OR fecha_nacimiento >= DATE '1900-01-01'),
    CONSTRAINT ck_ad_email  CHECK (email_contacto IS NULL
                                   OR email_contacto ~* '^[^@[:space:]]+@[^@[:space:]]+\.[^@[:space:]]+$')
);

-- 2. PELICULAS (entidad de apoyo, necesaria para la 3FN)
CREATE TABLE peliculas (
    id_pelicula    INTEGER GENERATED BY DEFAULT AS IDENTITY,
    titulo         VARCHAR(150) NOT NULL,
    genero         VARCHAR(50)  NOT NULL,
    duracion_min   INTEGER      NOT NULL,
    clasificacion  VARCHAR(10),
    anio_estreno   INTEGER,
    idioma         VARCHAR(40),
    CONSTRAINT pk_peliculas      PRIMARY KEY (id_pelicula),
    CONSTRAINT ck_peliculas_tit  CHECK (btrim(titulo) <> ''),
    CONSTRAINT ck_peliculas_dur  CHECK (duracion_min > 0 AND duracion_min <= 600),
    CONSTRAINT ck_peliculas_anio CHECK (anio_estreno IS NULL OR anio_estreno BETWEEN 1888 AND 2100)
);

-- 3. SALAS
CREATE TABLE salas (
    id_sala    INTEGER GENERATED BY DEFAULT AS IDENTITY,
    nombre     VARCHAR(50) NOT NULL,
    tipo       VARCHAR(5)  NOT NULL,
    capacidad  INTEGER     NOT NULL,
    estado     VARCHAR(15) NOT NULL DEFAULT 'Activa',
    CONSTRAINT pk_salas        PRIMARY KEY (id_sala),
    CONSTRAINT uq_salas_nombre UNIQUE (nombre),
    CONSTRAINT ck_salas_tipo   CHECK (tipo IN ('2D', '3D', 'VIP')),
    CONSTRAINT ck_salas_cap    CHECK (capacidad > 0 AND capacidad <= 250),
    CONSTRAINT ck_salas_estado CHECK (estado IN ('Activa', 'Mantenimiento'))
);

-- 4. STAFF
CREATE TABLE staff (
    id_staff         INTEGER GENERATED BY DEFAULT AS IDENTITY,
    documento        VARCHAR(20)   NOT NULL,
    nombre_completo  VARCHAR(150)  NOT NULL,
    cargo            VARCHAR(20)   NOT NULL,
    fecha_ingreso    DATE          NOT NULL DEFAULT CURRENT_DATE,
    salario          NUMERIC(12,2) NOT NULL,
    estado           VARCHAR(10)   NOT NULL DEFAULT 'Activo',
    CONSTRAINT pk_staff           PRIMARY KEY (id_staff),
    CONSTRAINT uq_staff_documento UNIQUE (documento),
    CONSTRAINT ck_staff_cargo     CHECK (cargo IN ('Taquillero', 'Acomodador', 'Proyeccionista', 'Gerente')),
    CONSTRAINT ck_staff_salario   CHECK (salario > 0),
    CONSTRAINT ck_staff_estado    CHECK (estado IN ('Activo', 'Inactivo')),
    CONSTRAINT ck_staff_ingreso   CHECK (fecha_ingreso >= DATE '1990-01-01')
);

-- 5. TIPOS_BOLETA
CREATE TABLE tipos_boleta (
    id_tipo_boleta        INTEGER GENERATED BY DEFAULT AS IDENTITY,
    nombre                VARCHAR(40)  NOT NULL,
    porcentaje_descuento  NUMERIC(5,2) NOT NULL DEFAULT 0,
    descripcion           VARCHAR(200),
    CONSTRAINT pk_tipos_boleta     PRIMARY KEY (id_tipo_boleta),
    CONSTRAINT uq_tipos_boleta_nom UNIQUE (nombre),
    CONSTRAINT ck_tipos_boleta_dto CHECK (porcentaje_descuento BETWEEN 0 AND 100)
);

-- 6. ESPECTADORES
CREATE TABLE espectadores (
    id_espectador     INTEGER GENERATED BY DEFAULT AS IDENTITY,
    documento         VARCHAR(20)  NOT NULL,
    nombre_completo   VARCHAR(150) NOT NULL,
    email             VARCHAR(150),
    fecha_nacimiento  DATE,
    fecha_registro    DATE         NOT NULL DEFAULT CURRENT_DATE,
    CONSTRAINT pk_espectadores     PRIMARY KEY (id_espectador),
    CONSTRAINT uq_espectadores_doc UNIQUE (documento),
    CONSTRAINT ck_esp_nombre       CHECK (btrim(nombre_completo) <> ''),
    CONSTRAINT ck_esp_email        CHECK (email IS NULL
                                          OR email ~* '^[^@[:space:]]+@[^@[:space:]]+\.[^@[:space:]]+$'),
    CONSTRAINT ck_esp_nacim        CHECK (fecha_nacimiento IS NULL OR fecha_nacimiento >= DATE '1900-01-01')
);

-- 7. CONTRATOS  (asociativa: actores_directores <-> peliculas)
CREATE TABLE contratos (
    id_contrato        INTEGER GENERATED BY DEFAULT AS IDENTITY,
    id_actor_director  INTEGER       NOT NULL,
    id_pelicula        INTEGER       NOT NULL,
    tipo_contrato      VARCHAR(20)   NOT NULL,
    fecha_inicio       DATE          NOT NULL,
    fecha_fin          DATE          NOT NULL,
    valor              NUMERIC(12,2) NOT NULL,
    estado             VARCHAR(15)   NOT NULL DEFAULT 'Vigente',
    CONSTRAINT pk_contratos        PRIMARY KEY (id_contrato),
    CONSTRAINT fk_contratos_actor  FOREIGN KEY (id_actor_director) REFERENCES actores_directores (id_actor_director),
    CONSTRAINT fk_contratos_peli   FOREIGN KEY (id_pelicula)       REFERENCES peliculas (id_pelicula),
    CONSTRAINT ck_contratos_tipo   CHECK (tipo_contrato IN ('Presentacion', 'Charla', 'Ciclo')),
    CONSTRAINT ck_contratos_fechas CHECK (fecha_fin >= fecha_inicio),
    CONSTRAINT ck_contratos_valor  CHECK (valor >= 0),
    CONSTRAINT ck_contratos_estado CHECK (estado IN ('Vigente', 'Finalizado', 'Cancelado'))
);

-- 8. FUNCIONES
--    fecha_hora_fin es derivable (inicio + duración de la película);
--    se conserva para validar cruces de horario y un trigger la calcula.
CREATE TABLE funciones (
    id_funcion         INTEGER GENERATED BY DEFAULT AS IDENTITY,
    id_sala            INTEGER       NOT NULL,
    id_pelicula        INTEGER       NOT NULL,
    fecha_hora_inicio  TIMESTAMP     NOT NULL,
    fecha_hora_fin     TIMESTAMP     NOT NULL,
    precio_base        NUMERIC(10,2) NOT NULL,
    estado             VARCHAR(15)   NOT NULL DEFAULT 'Programada',
    CONSTRAINT pk_funciones        PRIMARY KEY (id_funcion),
    CONSTRAINT fk_funciones_sala   FOREIGN KEY (id_sala)     REFERENCES salas (id_sala),
    CONSTRAINT fk_funciones_peli   FOREIGN KEY (id_pelicula) REFERENCES peliculas (id_pelicula),
    CONSTRAINT ck_funciones_horas  CHECK (fecha_hora_fin > fecha_hora_inicio),
    CONSTRAINT ck_funciones_precio CHECK (precio_base >= 0),
    CONSTRAINT ck_funciones_estado CHECK (estado IN ('Programada', 'En curso', 'Finalizada', 'Cancelada'))
);

-- 9. VENTAS  (cabecera de la compra)
--    id_staff es opcional: las ventas en línea no tienen taquillero.
CREATE TABLE ventas (
    id_venta       INTEGER GENERATED BY DEFAULT AS IDENTITY,
    id_espectador  INTEGER     NOT NULL,
    id_staff       INTEGER,
    fecha_hora     TIMESTAMP   NOT NULL DEFAULT CURRENT_TIMESTAMP,
    canal          VARCHAR(10) NOT NULL,
    estado         VARCHAR(10) NOT NULL DEFAULT 'Pagada',
    CONSTRAINT pk_ventas          PRIMARY KEY (id_venta),
    CONSTRAINT fk_ventas_espec    FOREIGN KEY (id_espectador) REFERENCES espectadores (id_espectador),
    CONSTRAINT fk_ventas_staff    FOREIGN KEY (id_staff)      REFERENCES staff (id_staff),
    CONSTRAINT ck_ventas_canal    CHECK (canal IN ('Presencial', 'Online')),
    CONSTRAINT ck_ventas_estado   CHECK (estado IN ('Pagada', 'Anulada')),
    -- una venta presencial siempre la registra un empleado
    CONSTRAINT ck_ventas_taquilla CHECK (canal <> 'Presencial' OR id_staff IS NOT NULL)
);

-- 10. DETALLE_VENTAS  (asociativa: ventas <-> funciones, con tipo de boleta)
--     precio_unitario es el precio final cobrado (precio base con
--     descuento) y se conserva como dato histórico. El total se calcula
--     como cantidad * precio_unitario.
CREATE TABLE detalle_ventas (
    id_detalle       INTEGER GENERATED BY DEFAULT AS IDENTITY,
    id_venta         INTEGER       NOT NULL,
    id_funcion       INTEGER       NOT NULL,
    id_tipo_boleta   INTEGER       NOT NULL,
    cantidad         INTEGER       NOT NULL,
    precio_unitario  NUMERIC(10,2) NOT NULL,
    CONSTRAINT pk_detalle_ventas   PRIMARY KEY (id_detalle),
    CONSTRAINT uq_detalle_linea    UNIQUE (id_venta, id_funcion, id_tipo_boleta),
    CONSTRAINT fk_detalle_venta    FOREIGN KEY (id_venta)       REFERENCES ventas (id_venta),
    CONSTRAINT fk_detalle_funcion  FOREIGN KEY (id_funcion)     REFERENCES funciones (id_funcion),
    CONSTRAINT fk_detalle_tipo     FOREIGN KEY (id_tipo_boleta) REFERENCES tipos_boleta (id_tipo_boleta),
    CONSTRAINT ck_detalle_cantidad CHECK (cantidad > 0),
    CONSTRAINT ck_detalle_precio   CHECK (precio_unitario >= 0)
);

-- 11. FUNCION_STAFF  (asociativa: funciones <-> staff, con su rol)
CREATE TABLE funcion_staff (
    id_funcion_staff  INTEGER GENERATED BY DEFAULT AS IDENTITY,
    id_funcion        INTEGER     NOT NULL,
    id_staff          INTEGER     NOT NULL,
    rol_en_funcion    VARCHAR(15) NOT NULL,
    CONSTRAINT pk_funcion_staff   PRIMARY KEY (id_funcion_staff),
    CONSTRAINT uq_funcion_staff   UNIQUE (id_funcion, id_staff),
    CONSTRAINT fk_fs_funcion      FOREIGN KEY (id_funcion) REFERENCES funciones (id_funcion),
    CONSTRAINT fk_fs_staff        FOREIGN KEY (id_staff)   REFERENCES staff (id_staff),
    CONSTRAINT ck_fs_rol          CHECK (rol_en_funcion IN ('Responsable', 'Proyeccion', 'Acomodacion'))
);

-- ÍNDICES BÁSICOS (las PK y UNIQUE ya crean su propio índice)
-- Correos únicos sin distinguir mayúsculas
CREATE UNIQUE INDEX uq_esp_email_lower ON espectadores (lower(email));
CREATE UNIQUE INDEX uq_ad_email_lower  ON actores_directores (lower(email_contacto));
-- Validación de cruces de horario por sala
CREATE INDEX idx_funciones_sala_inicio ON funciones (id_sala, fecha_hora_inicio);
CREATE INDEX idx_funciones_pelicula    ON funciones (id_pelicula);
-- Ventas y su detalle: reportes y control de capacidad
CREATE INDEX idx_ventas_espectador     ON ventas (id_espectador);
CREATE INDEX idx_ventas_staff          ON ventas (id_staff) WHERE id_staff IS NOT NULL;
CREATE INDEX idx_detalle_venta         ON detalle_ventas (id_venta);
CREATE INDEX idx_detalle_funcion       ON detalle_ventas (id_funcion);
CREATE INDEX idx_detalle_tipo          ON detalle_ventas (id_tipo_boleta);
-- Contratos por artista y por película
CREATE INDEX idx_contratos_actor       ON contratos (id_actor_director);
CREATE INDEX idx_contratos_pelicula    ON contratos (id_pelicula);
-- Personal por función
CREATE INDEX idx_fs_staff              ON funcion_staff (id_staff);

-- VERIFICACIÓN (útil para la captura de evidencia)
SELECT table_name AS tabla,
       (SELECT COUNT(*) FROM information_schema.columns c
         WHERE c.table_name = t.table_name AND c.table_schema = 'public') AS columnas
FROM information_schema.tables t
WHERE table_schema = 'public' AND table_type = 'BASE TABLE'
ORDER BY table_name;